# Script to run germline:somatic experiment P-NET on pre-formatted prostate germline and/or somatic data
# Author: Gwen Miller
# Related to the `run_pnet.py` script, which was generated by copying over and then editing everything in the file: `pnet/notebooks/prostate_metastatic_prediction_example.ipynb`

import logging
import os
import warnings

import configargparse
import numpy as np
import pandas as pd
import torch
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import StratifiedKFold

import wandb
from pnet import Pnet, pnet_loader, report_and_eval, model_selection
from pnet.utils import modeling_utils

warnings.simplefilter(action="ignore", category=FutureWarning)


logging.basicConfig(
    encoding="utf-8",
    format="%(asctime)s %(levelname)-8s [%(name)s] %(message)s",
    level=logging.INFO,
    datefmt="%Y-%m-%d %H:%M:%S",
    force=True,
)

logger = logging.getLogger(__name__)


def parse_arguments():
    parser = configargparse.ArgumentParser(description="Description of your script")
    parser.add(
        "--config_f",
        type=str,
        required=False,
        is_config_file=True,
        help="Path to a config file",
    )
    parser.add(
        "--data_config_f",
        type=str,
        required=True,
        is_config_file=False,
        help="Path to a config file",
    )
    parser.add(
        "--datasets",
        default=["somatic_amp", "somatic_del", "somatic_mut"],
        help="List of datasets to use",
        action=modeling_utils.ParseAction,
    )  # NOTE: I don't use nargs = "+" because it doesn't work with wandb sweep
    parser.add(
        "--evaluation_set",
        default="validation",
        choices=["validation", "test"],
        help="Evaluation set (validation or test)",
    )
    parser.add(
        "--model_type",
        default="bdt",
        choices=["bdt", "rf", "pnet", "logistic_regression", "sgd_logistic_regression"],
        help="Type of model",
    )
    parser.add("--wandb_group", default="", help="Wandb group name")
    parser.add(
        "--wandb_project", default="prostate_met_status", help="Wandb group name"
    )
    parser.add("--seed", type=int, default=123, help="Seed value")
    parser.add("--input_data_dir", help="Directory with model-ready data")
    parser.add(
        "--data_split_dir",  # TODO: remove hard-coded default path
        default="/mnt/disks/gmiller_data1/pnet_germline/data/pnet_database/prostate/splits",
        help="Directory with data split files",
    )
    parser.add(
        "--input_data_wandb_id",
        default="",
        help="W&B run ID that created the data in the input_data_dir, if applicable",
    )
    parser.add(
        "--cpus",
        type=int,
        required=False,
        help="Define the number of CPUs PyTorch uses during parallelization tasks",
    )
    parser.add(
        "--input_dropout",
        default=0.5,
        type=float,
        help="Proportion of dropout between the input layer and gene layer",
    )
    parser.add(
        "--h1_alpha",
        default=0,
        type=float,
        help="Strength of regularization on weights going to the first hidden layer (genes); default to no regularization",
    )
    parser.add(
        "--h1_regularization_method",
        default="l1",
        choices=["l1", "l2", "elasticnet"],
        help="Type of regularization on weights going to the first hidden layer (genes)",
    )
    parser.add(
        "--l1_ratio",
        required=False,
        default=0.5,
        type=float,
        help="Control the amount of L1 vs L2 regularization when using ElasticNet",
    )
    parser.add(
        "--epochs",
        type=int,
        default=500,
        help="Number of epochs to train the model (default: 500)",
    )
    parser.add(
        "--max_depth",
        type=int,
        default=None,
        help="Maximum depth of the tree for Random Forest (default: None, which means no limit. Use with caution as it can lead to overfitting)",
    )
    parser.add(
        "--min_samples_leaf",
        type=int,
        default=1,
        help="Minimum number of samples required to be at a leaf node for Random Forest (default: 1)",
    )
    parser.add(
        "--min_samples_split",
        type=int,
        default=50,
        help="Define the min number of samples used to make RF split (best practice usually 5-10% of dataset)",
    )
    parser.add(
        "--weight_decay",
        type=float,
        default=1e-3,
        help="Weight decay for optimizer regularization (default: 1e-3)",
    )
    parser.add(
        "--lr",
        type=float,
        default=1e-3,
        help="Learning rate for optimizer (default: 1e-3)",
    )
    parser.add(
        "--dropout",
        type=float,
        default=0.2,
        help="Dropout rate for neural network layers (default: 0.2)",
    )
    parser.add(
        "--batch_size",
        type=int,
        default=64,
        help="Batch size for training (default: 64)",
    )
    parser.add(
        "--early_stopping_patience",
        type=int,
        default=50,
        help="Early stopping patience (number of epochs with no improvement before stopping) (default: 50)",
    )
    parser.add(
        "--class_weight",
        type=str,
        default="none",
        choices=["none", "balanced"],
        help="Class weighting strategy: 'none' for no weighting, 'balanced' for inverse frequency weighting (default: none)",
    )
    parser.add(
        "--l1_penalty",
        type=float,
        default=1.0,
        help="Inverse of regularization strength for logistic regression (C parameter). Lower values indicate stronger regularization. Only applies to logistic_regression model type (default: 1.0)",
    )
    parser.add(
        "--logistic_penalty_type",
        type=str,
        default="l1",
        choices=["l1", "l2", "elasticnet"],
        help="Type of penalty for logistic regression: 'l1' (Lasso), 'l2' (Ridge), or 'elasticnet' (combination). Only applies to logistic_regression model type (default: l1)",
    )
    parser.add(
        "--logistic_l1_ratio",
        type=float,
        default=0.5,
        help="Balance between L1 and L2 regularization when using elasticnet penalty (0 to 1). 0 = pure L2, 1 = pure L1. Only applies to logistic_regression model type (default: 0.5)",
    )
    parser.add(
        "--split_strategy",
        type=str,
        default="files",
        choices=["files", "cv"],
        help="Use predefined split files, or run stratified K-fold CV on the non-test pool.",
    )
    parser.add(
        "--cv_folds",
        type=int,
        default=5,
        help="Number of CV folds (only used when split_strategy=cv).",
    )
    parser.add(
        "--cv_shuffle",
        default=True,
        help="Shuffle before splitting folds (recommended).",
    )
    parser.add(
        "--cv_seed",
        type=int,
        default=None,
        help="Seed for CV splitter. Defaults to --seed if not set.",
    )
    parser.add(
        "--cv_log_per_fold_runs",
        action="store_true",
        help="If set, create a separate W&B run per fold instead of logging all folds into one run.",
    )

    return parser.parse_args()


def load_input_data(config, input_dir):
    """Load genetic, confounder, and target data from disk."""
    genetic_data = {}
    for name, info in config["genetic_data"].items():
        path = os.path.join(input_dir, info["filename"])
        df = pd.read_csv(path, index_col=0)
        genetic_data[name] = df

    confounder_df = pd.read_csv(
        os.path.join(input_dir, config["confounder_data"]["filename"]), index_col=0
    )
    target_df = pd.read_csv(
        os.path.join(input_dir, config["target"]["filename"]), index_col=0
    )

    return genetic_data, confounder_df, target_df


def calculate_class_weights(y, strategy="balanced"):
    """
    Calculate class weights for imbalanced datasets.

    Args:
        y: Target labels (array-like)
        strategy: 'balanced' for inverse frequency weighting

    Returns:
        torch.Tensor of class weights, or None if strategy is 'none'
    """
    if strategy == "none":
        return None

    # Get unique classes and ensure they are 0-indexed and contiguous
    unique_classes = np.unique(y)
    logger.info(f"Unique classes: {unique_classes}")

    # Validate that classes are 0, 1, 2, ...
    expected_classes = np.arange(len(unique_classes))
    if not np.array_equal(unique_classes, expected_classes):
        raise ValueError(
            f"Classes must be 0-indexed and contiguous (0, 1, 2, ...). "
            f"Found: {unique_classes}. Expected: {expected_classes}"
        )

    if strategy == "balanced":
        class_weights = compute_class_weight("balanced", classes=unique_classes, y=y)
        logger.info(f"Calculated balanced class weights: {class_weights}")
        return torch.tensor(class_weights, dtype=torch.float32)

    return None


def main():
    args = parse_arguments()
    wandb.login()
    wandb.init(project=args.wandb_project, group=args.wandb_group)

    logger.info(f"Starting run with ID: {wandb.run.id}")
    # Set environment
    Pnet.set_random_seeds(args.seed, turn_off_cuDNN=False)
    # Only set PyTorch thread count when user provided a value
    if args.cpus:
        torch.set_num_threads(int(args.cpus))

    # Setup save path
    save_dir = modeling_utils.setup_save_dir(
        args.model_type, args.evaluation_set, args.wandb_group, wandb.run.id
    )

    # Load config and data
    config = modeling_utils.read_config(args.data_config_f)
    genetic_data, confounder_df, y = load_input_data(config, args.input_data_dir)
    genetic_data = {k: v for k, v in genetic_data.items() if k in args.datasets}

    # --- QUICK DIRTY 5-FOLD CV (fixed test set) ---

    # Load splits once (fixed test)
    train_inds, validation_inds, test_inds = modeling_utils.get_train_val_test_indices(
        args.data_split_dir
    )

    # get canonical IDs present across modalities
    inds = pnet_loader.get_indicies(genetic_data, y, confounder_df)

    # CV indices to use: everything except test
    non_test_inds = np.asarray(
        list(set(inds).intersection(set(train_inds).union(set(validation_inds))))
    )
    # keep just the ones that overlap
    logger.info(f"non_test_inds: {non_test_inds[:10]}... (n={len(non_test_inds)})")
    logger.info(f"y indices: {y.index.values[:10]}... (n={len(y)})")

    cv_seed = args.cv_seed if args.cv_seed is not None else args.seed
    skf = StratifiedKFold(
        n_splits=args.cv_folds, shuffle=args.cv_shuffle, random_state=cv_seed
    )

    # Build test dataset once (fixed)
    test_dataset = pnet_loader.generate_dataset_from_indices(
        genetic_data=genetic_data,
        target=y,
        dset_inds=test_inds,
        additional_data=confounder_df,
        gene_set=None,
        seed=args.seed,
    )
    # Patch test dataset for sklearn-style models
    test_dataset.input_df = pd.concat(
        [test_dataset.input_df, test_dataset.additional_data], axis=1
    )
    test_dataset.x = torch.cat([test_dataset.x, test_dataset.additional], dim=1)

    fold_rows = []
    for fold_i, (train_pos, val_pos) in enumerate(
        skf.split(np.zeros(len(non_test_inds)), y.loc[non_test_inds])
    ):
        fold_train_inds = non_test_inds[train_pos].tolist()
        fold_val_inds = non_test_inds[val_pos].tolist()

        logger.info(
            f"=== CV fold {fold_i + 1}/{args.cv_folds} === "
            f"train={len(fold_train_inds)} val={len(fold_val_inds)} test={len(test_inds)}"
        )

        # per-fold save dir
        fold_save_dir = os.path.join(save_dir, f"cv_fold_{fold_i:02d}")
        os.makedirs(fold_save_dir, exist_ok=True)

        # Build fold datasets
        train_dataset, validation_dataset = pnet_loader.generate_train_test(
            genetic_data,
            additional_data=confounder_df,
            target=y,
            train_inds=fold_train_inds,
            test_inds=fold_val_inds,
            gene_set=None,
            seed=args.seed,
        )

        # Patch for sklearn expectations
        train_dataset.input_df = pd.concat(
            [train_dataset.input_df, train_dataset.additional_data], axis=1
        )
        train_dataset.x = torch.cat([train_dataset.x, train_dataset.additional], dim=1)

        validation_dataset.input_df = pd.concat(
            [validation_dataset.input_df, validation_dataset.additional_data], axis=1
        )
        validation_dataset.x = torch.cat(
            [validation_dataset.x, validation_dataset.additional], dim=1
        )

        # Train
        x_train, y_train = train_dataset.x, train_dataset.y.ravel()
        model = model_selection.run_logistic_regression_sgd(
            x_train,
            y_train,
            loss="log_loss",
            penalty=args.logistic_penalty_type,
            C=args.l1_penalty,
            alpha=0.01,
            class_weight={0: 0.75, 1: 1.5},
            l1_ratio=args.logistic_l1_ratio
            if args.logistic_penalty_type == "elasticnet"
            else 0.15,  # use default 0.15 when not elasticnet, because will be ignored. Setting to None will error out.
            random_seed=args.seed,
        )

        # Evaluate + save metrics JSONs under fold dir
        report_and_eval.evaluate_interpret_save(
            model=model,
            who="validation",
            model_type="sgd_logistic_regression",
            pnet_dataset=validation_dataset,
            save_dir=fold_save_dir,
            log_to_wandb=False,
        )
        report_and_eval.evaluate_interpret_save(
            model=model,
            who="test",
            model_type="sgd_logistic_regression",
            pnet_dataset=test_dataset,
            save_dir=fold_save_dir,
            log_to_wandb=False,
        )

        # Read back scalar metrics (quick & dirty)
        val_md = pd.read_json(
            os.path.join(fold_save_dir, "validation_performance_metrics.json"),
            typ="series",
        )
        test_md = pd.read_json(
            os.path.join(fold_save_dir, "test_performance_metrics.json"), typ="series"
        )

        val_auprc = float(val_md["validation_average_precision_score"])
        val_auc = float(val_md["validation_roc_auc_score"])
        test_auprc = float(test_md["test_average_precision_score"])
        test_auc = float(test_md["test_roc_auc_score"])

        fold_rows.append(
            {
                "fold": fold_i,
                "val_auprc": val_auprc,
                "val_roc_auc": val_auc,
                "test_auprc": test_auprc,
                "test_roc_auc": test_auc,
                "train_n": len(fold_train_inds),
                "val_n": len(fold_val_inds),
                "test_n": len(test_inds),
            }
        )

        wandb.log(
            {
                f"cv/fold_{fold_i:02d}/val_auprc": val_auprc,
                f"cv/fold_{fold_i:02d}/val_auc": val_auc,
                f"cv/fold_{fold_i:02d}/test_auprc": test_auprc,
                f"cv/fold_{fold_i:02d}/test_auc": test_auc,
            }
        )

        logger.info(
            f"Fold {fold_i:02d} "
            f"VAL AUPRC={val_auprc:.4f} VAL AUROC={val_auc:.4f} | "
            f"TEST AUPRC={test_auprc:.4f} TEST AUROC={test_auc:.4f}"
        )

    # Summarize after loop
    df = pd.DataFrame(fold_rows).sort_values("fold")
    logger.info("=== CV summary (validation) ===")
    logger.info(df[["fold", "val_auprc", "val_roc_auc"]].to_string(index=False))
    logger.info(
        f"VAL AUPRC mean={df.val_auprc.mean():.4f} std={df.val_auprc.std(ddof=1):.4f}\n"
        f"VAL AUROC mean={df.val_roc_auc.mean():.4f} std={df.val_roc_auc.std(ddof=1):.4f}"
    )
    # add same for test
    logger.info("=== CV summary (test) ===")
    logger.info(df[["fold", "test_auprc", "test_roc_auc"]].to_string(index=False))
    logger.info(
        f"TEST AUPRC mean={df.test_auprc.mean():.4f} std={df.test_auprc.std(ddof=1):.4f}\n"
        f"TEST AUROC mean={df.test_roc_auc.mean():.4f} std={df.test_roc_auc.std(ddof=1):.4f}"
    )
    wandb.log(
        {
            "cv/val_auprc_mean": df.val_auprc.mean(),
            "cv/val_auprc_std": df.val_auprc.std(ddof=1),
            "cv/val_roc_auc_mean": df.val_roc_auc.mean(),
            "cv/val_roc_auc_std": df.val_roc_auc.std(ddof=1),
            # add the same but for test
            "cv/test_auprc_mean": df.test_auprc.mean(),
            "cv/test_auprc_std": df.test_auprc.std(ddof=1),
            "cv/test_roc_auc_mean": df.test_roc_auc.mean(),
            "cv/test_roc_auc_std": df.test_roc_auc.std(ddof=1),
        }
    )

    # Identify best-performing fold by validation AUPRC
    best_row = df.loc[df["val_auprc"].idxmax()]
    best_fold = int(best_row["fold"])

    logger.info(
        f"Best fold by validation AUPRC: fold {best_fold} "
        f"(val_auprc={best_row['val_auprc']:.4f}, "
        f"test_auprc={best_row['test_auprc']:.4f})"
    )
    best_fold_dir = os.path.join(save_dir, f"cv_fold_{best_fold:02d}")
    logger.info(f"Best fold artifacts located at: {best_fold_dir}")

    wandb.log(
        {
            "cv/best_fold": best_fold,
            "cv/best_val_auprc": best_row["val_auprc"],
            "cv/best_val_roc_auc": best_row["val_roc_auc"],
            "cv/best_test_auprc": best_row["test_auprc"],
            "cv/best_test_roc_auc": best_row["test_roc_auc"],
        }
    )

    out_csv = os.path.join(save_dir, "cv_5fold_lr_metrics.csv")
    df.to_csv(out_csv, index=False)
    logger.info(f"Saved CV metrics to {out_csv}")
    # --- END QUICK DIRTY CV ---

    wandb.finish()
    return


if __name__ == "__main__":
    main()
